export const apiToDisplay = {
  componentId: "Component",
  rlCategory: "RL Category",
  rlNumber: "RL Number",
  descriptions: "Description",
  manufacturer: "Manufacturer",
  partNumber: "Part Number",
  stockCode: "Stock Code",
  electricalAddress: "Electrical Address",
  componentApplication: "Component Application",
  referenceTag: "Reference Tag",
  settings: "Settings",
  image: "Image",
  resources: "Resources",
  cutsheet: "Cutsheet",
  maintenanceVideo: "Maintenance Video",
};

export const csvToApi = {
  Component: "componentId",
  "RL Category": "rlCategory",
  "RL Number": "rlNumber",
  Description: "descriptions",
  Manufacturer: "manufacturer",
  "Part Number": "partNumber",
  "Stock Code": "stockCode",
  "Electrical Address": "electricalAddress",
  "Component Application": "componentApplication",
  "Reference Tag": "referenceTag",
  Settings: "settings",
  Image: "image",
  Resources: "resources",
  Cutsheet: "cutsheet",
  "Maintenance Video": "maintenanceVideo",
};

export const headerKeys = [
  { key: "componentId", label: "Component" },
  { key: "rlCategory", label: "RL Category" },
  { key: "rlNumber", label: "RL Number" },
  { key: "descriptions", label: "Description" },
  { key: "manufacturer", label: "Manufacturer" },
  { key: "partNumber", label: "Part Number" },
  { key: "stockCode", label: "Stock Code" },
  { key: "electricalAddress", label: "Electrical Address" },
  { key: "componentApplication", label: "Component Application" },
  { key: "referenceTag", label: "Reference Tag" },
  { key: "settings", label: "Settings" },
  { key: "image", label: "Image" },
  { key: "resources", label: "Resources" },
  { key: "cutsheet", label: "Cutsheet" },
  { key: "maintenanceVideo", label: "Maintenance Video" },
];
