# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on: [push, pull_request]

# The jobs that will be run, usually in parallel
jobs:
  # A job to generate and publish code coverage
  coverage:
    # A more descriptive name of the job
    name: Test and publish test coverage

    # The OS on which the job will run
    runs-on:
      ubuntu-16.04
      # The steps for the job, executed in sequence
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: yarn start:coverage

      # A GitHub action for running tests and publishing coverage
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          # An environment variable, the value is a GitHub repo secret
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
          #CC_TEST_REPORTER_ID: 12dcfce279bc5c9eb9fa7ba358ecbe48a525ce91187812cfc5c50f008045bc57
        with:
          # Run our `coverage` command from our `package.json`
          coverageCommand: yarn help
          debug: true
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
